joint_names: ["head_axis_joint"]
action_name: /head/joint_trajectory_controller/follow_joint_trajectory
service_ns: /head/driver
default_vel: 0.5

front_face: [[-0.471]]
front_face_sit: [[0.09027]]
back_table: [[-3.441]]

