<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

	<include filename="$(find mdr_description)/urdf/base/volksbot/base.gazebo.xacro" />
	<include filename="$(find mdr_description)/urdf/base/volksbot/base.transmission.xacro" />
	<include filename="$(find mcr_description)/urdf/sensors/sick_lms_200.urdf.xacro"/>
	<include filename="$(find mcr_description)/urdf/sensors/hokuyo_lx30.urdf.xacro"/> 
	
	
	<!-- base -->
	<property name="base_width" value="0.5" />
	<property name="base_depth" value="0.5" />

	<!-- wheels -->
	<!-- center of the front wheel as offset from the base link -->
	<property name="front_wheel_x" value="0.18" />
	<property name="front_wheel_y" value="0.225" />
	<property name="front_wheel_z" value="-0.027" />
	
	<!-- mounting point of the rear caster wheels from the base link -->
	<property name="rear_caster_x" value="0.18" />
	<property name="rear_caster_y" value="0.18" />
	<property name="rear_caster_z" value="0.0" />
	
	<!-- offset from the caster wheel's mounting point to the center of the rear wheels -->
	<property name="rear_wheel_offset_x" value="-0.04" />	<!-- this is approximately the rear wheels' radius -->
	<property name="rear_wheel_offset_y" value="0.0" />
	<property name="rear_wheel_offset_z" value="-0.065" />	<!-- constraint: abs(rear_wheel_offset_z) + rear_wheel_radius = front_wheel_radius -->
	
	<property name="front_wheel_length" value="0.04" />
	<property name="front_wheel_radius" value="0.07" />
	<property name="rear_wheel_length" value="0.023" />
	<property name="rear_wheel_radius" value="0.03" />
	
	<!-- laser -->
	<property name="base_laser_front_x" value="0.215" />
	<property name="base_laser_front_y" value="0.0" />
	<property name="base_laser_front_z" value="0.08" />
	
	<property name="base_laser_rear_x" value="-0.275" />
	<property name="base_laser_rear_y" value="0.0" />
	<property name="base_laser_rear_z" value="0.02" />
	
	

	<xacro:macro name="volksbot_front_wheel" params="suffix parent *origin reflect ref_position">
		<link name="${parent}_${suffix}_front_wheel_link">
			<inertial>
				<mass value="1" />
				<origin xyz="0 0 0" />
				<inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
			</inertial>
			
			<visual>
				<origin xyz="0 0 0" rpy="${M_PI / 2} 0 0" />
				<geometry>
					<cylinder length="${front_wheel_length}" radius="${front_wheel_radius}"/>
				</geometry>
				<material name="Grey" />
			</visual>
			
			<collision>
				<origin xyz="0 0 0" rpy="${M_PI / 2} 0 0" />
				<geometry>
					<cylinder length="${front_wheel_length}" radius="${front_wheel_radius}"/>
				</geometry>
			</collision>
		</link>
		
		<joint name="${parent}_${suffix}_front_wheel_joint" type="continuous">
			<parent link="${parent}"/>
			<child link="${parent}_${suffix}_front_wheel_link"/>
			<axis xyz="0 1 0"/>
			<insert_block name="origin"/>
			<limit effort="100" velocity="100"/>
			<safety_controller  k_velocity="10"/>
			<dynamics damping="0" friction="0"/>
		</joint>
		
		<xacro:volksbot_front_wheel_gazebo parent="${parent}" suffix="${suffix}" />
		<xacro:volksbot_front_wheel_transmission parent="${parent}" suffix="${suffix}" reflect="${reflect}" />
	</xacro:macro>


	<xacro:macro name="volksbot_rear_wheel" params="suffix parent *origin reflect ref_position">
		<link name="${suffix}_rotation_link">
			<inertial>
				<mass value="0.01" />
				<origin xyz="0 0 0" />
				<inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
			</inertial>
			
			<visual>
				<origin xyz="0.1 0 0" rpy="0 0 0" />
				<geometry>
					<box size="0.001 0.001 0.001"/>
				</geometry>
				<material name="Grey" />
			</visual>
			
			<collision>
				<origin xyz="0.1 0 0" rpy="0 0 0" />
				<geometry>
					<box size="0.001 0.001 0.001"/>
				</geometry>
			</collision>
		</link>
		
		<joint name="${suffix}_rotation_joint" type="continuous">
			<parent link="${parent}"/>
			<child link="${suffix}_rotation_link"/>
			<axis xyz="0 0 1"/>
			<insert_block name="origin"/>
			<calibration rising="${ref_position}" />
			<limit effort="100" velocity="100"/>
			<safety_controller  k_velocity="10" />
			<dynamics damping="0" friction="0" />
		</joint>
		
		<link name="${parent}_${suffix}_rear_wheel_link">
			<inertial>
				<mass value="1" />
				<origin xyz="0 0 0" />
				<inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
			</inertial>
			
			<visual>
				<origin xyz="0 0 0" rpy="${M_PI / 2} 0 0" />
				<geometry>
					<cylinder length="${rear_wheel_length}" radius="${rear_wheel_radius}"/>
				</geometry>
				<material name="Grey" />
			</visual>
			
			<collision>
				<origin xyz="0 0 0" rpy="${M_PI / 2} 0 0" />
				<geometry>
					<cylinder length="${rear_wheel_length}" radius="${rear_wheel_radius}"/>
				</geometry>
			</collision>
		</link>
		
		<joint name="${parent}_${suffix}_rear_wheel_joint" type="continuous">
			<parent link="${suffix}_rotation_link"/>
			<child link="${parent}_${suffix}_rear_wheel_link"/>
			<axis xyz="0 1 0"/>
			<origin xyz="${rear_wheel_offset_x} ${rear_wheel_offset_y} ${rear_wheel_offset_z}" rpy="0 0 0"/>
			<limit effort="100" velocity="100"/>
			<safety_controller k_velocity="10" />
			<dynamics damping="0" friction="0" />
		</joint>
		
		<xacro:volksbot_rear_wheel_gazebo parent="${parent}" suffix="${suffix}" />
	</xacro:macro>


	<xacro:macro name="volksbot_base" params="name">
		
		<!-- base_footprint -->
		<link name="${name}_footprint">
			<inertial>
				<mass value="0.01" />
				<origin xyz="0 0 0" />
				<inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
			</inertial>
			
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<box size="0.001 0.001 0.001" />
				</geometry>
			</visual>
			
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<box size="0.001 0.001 0.001" />
				</geometry>
			</collision>
		</link>
		
		<!-- base_link -->
		<link name="${name}_link">
			<inertial>
				<mass value="30" />
				<origin xyz="0 0 0" />
				<inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
			</inertial>
			
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<box size="0.01 0.01 0.01" />
				</geometry>
				<material name="Red" />
			</visual>
			
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<box size="0.001 0.001 0.001" />
				</geometry>
			</collision>
		</link>
		<joint name="${name}_joint" type="fixed">
			<parent link="${name}_footprint"/>
			<child link="${name}_link"/>
			<origin xyz="0 0 0.1" rpy="0 0 0" />
		</joint>

		<!-- base -->
		<link name="${name}_lower_case_link">
			<inertial>
				<mass value="1" />
				<origin xyz="0 0 0" />
				<inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
			</inertial>
			
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<box size="${base_depth} ${base_width} 0.12"/>
				</geometry>
				<material name="Red" />
			</visual>
			
			<!-- decrease size of this link and shift it a bit back so that it does not block the laser -->
			<collision>
				<origin xyz="-0.035 0 0" rpy="0 0 0" />
				<geometry>
					<box size="${base_depth - 0.035} ${base_width} 0.12"/>
				</geometry>
			</collision>
		</link>
			
		<joint name="${name}_lower_case_joint" type="fixed">
			<parent link="${name}_link"/>
			<child link="${name}_lower_case_link"/>
			<origin xyz="0 0 0.06" rpy="0 0 0" />
		</joint>


		<link name="${name}_middle_case_link">
			<inertial>
				<mass value="1" />
				<origin xyz="0 0 0" />
				<inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
			</inertial>
			
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<box size="${base_depth} ${base_width} 0.14"/>
				</geometry>
				<material name="Green" />
			</visual>
			
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<box size="${base_depth} ${base_width} 0.14"/>
				</geometry>
			</collision>
		</link>

		<joint name="${name}_middle_case_joint" type="fixed">
			<parent link="${name}_lower_case_link"/>
			<child link="${name}_middle_case_link"/>
			<origin xyz="0 0 0.13" rpy="0 0 0" />
		</joint>


		<link name="${name}_upper_case_link">
			<inertial>
				<mass value="1" />
				<origin xyz="0 0 0" />
				<inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
			</inertial>
			
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<box size="${base_depth} ${base_width} 0.10"/>
				</geometry>
				<material name="Blue" />
			</visual>
			
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<box size="${base_depth} ${base_width} 0.10"/>
				</geometry>
			</collision>
		</link>
		
		<joint name="${name}_upper_case_joint" type="fixed">
			<parent link="${name}_middle_case_link"/>
			<child link="${name}_upper_case_link"/>
			<origin xyz="0 0 0.12" rpy="0 0 0" />
		</joint>

		<!-- base laser front -->
		<xacro:sick_lms_200 name="${name}_laser_front" parent="${name}" ros_topic="scan_front" update_rate="75" min_angle="-1.5708" max_angle="1.5708" >
			<origin xyz="${base_laser_front_x} ${base_laser_front_y} ${base_laser_front_z}" rpy="0 0 0" />
		</xacro:sick_lms_200>
		
		<!-- base rear front -->
		<xacro:hokuyo_lx30 name="${name}_laser_rear" parent="${name}" ros_topic="scan_rear" update_rate="40" min_angle="-1.5708" max_angle="1.5708" >
			<origin xyz="${base_laser_rear_x} ${base_laser_rear_y} ${base_laser_rear_z}" rpy="${M_PI} 0 ${M_PI}" />
		</xacro:hokuyo_lx30>


		<xacro:volksbot_front_wheel suffix="l" parent="${name}_link" reflect="1" ref_position="${-M_PI/4}" >
			<origin xyz="${front_wheel_x} ${front_wheel_y} ${front_wheel_z}" rpy="0 0 ${M_PI}" />
		</xacro:volksbot_front_wheel>
		<xacro:volksbot_front_wheel suffix="r" parent="${name}_link" reflect="-1" ref_position="${-M_PI/4}" >
			<origin xyz="${front_wheel_x} ${-front_wheel_y} ${front_wheel_z}" rpy="0 0 ${M_PI}" />
		</xacro:volksbot_front_wheel>
		<xacro:volksbot_rear_wheel suffix="l" parent="${name}_link" reflect="1" ref_position="${-M_PI / 4 + M_PI}" >
			<origin xyz="${-rear_caster_x} ${rear_caster_y} ${rear_caster_z}" rpy="0 0 0" />
		</xacro:volksbot_rear_wheel>
		<xacro:volksbot_rear_wheel suffix="r" parent="${name}_link" reflect="-1" ref_position="${-M_PI / 4 + M_PI}" >
			<origin xyz="${-rear_caster_x} ${-rear_caster_y} ${rear_caster_z}" rpy="0 0 0" />
		</xacro:volksbot_rear_wheel>

		<xacro:volksbot_base_gazebo name="${name}" />
	</xacro:macro>

</robot>
