joint_names: ["ptu_pan_joint", "ptu_tilt_joint"]
home: [[0.0, 0.0]]
left: [[2.0, 0.0]]
right: [[-2.0, 0.0]]
front: [[0.0, -0.5]]
front_left: [[2.0, -0.5]]
front_right: [[-2.0, -0.5]]
back: [[0.0, 0.5]]
back_left: [[2.0, 0.5]]
back_right: [[-2.0, 0.5]]