controller_list:
  - name: arm_controller
    ns: /lwr_controller/joint_trajectory_controller
    type: FollowJointTrajectory
    default: true
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
      - arm_7_joint
  - name: sdh_controller
    ns: /sdh_controller/follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - sdh_finger_22_joint
      - sdh_finger_23_joint
      - sdh_knuckle_joint
      - sdh_finger_12_joint
      - sdh_finger_13_joint
      - sdh_thumb_2_joint
      - sdh_thumb_3_joint
  - name: tray_controller
    ns: /tray_controller/follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - tray_joint