controller_list:
  - name: fake_arm_controller
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
      - arm_7_joint
  - name: fake_head_controller
    joints:
      - torso_lower_neck_pan_joint
      - torso_lower_neck_tilt_joint
      - torso_upper_neck_pan_joint
      - torso_upper_neck_tilt_joint
      - head_axis_joint
  - name: fake_sdh_controller
    joints:
      - sdh_finger_22_joint
      - sdh_finger_23_joint
      - sdh_knuckle_joint
      - sdh_finger_12_joint
      - sdh_finger_13_joint
      - sdh_thumb_2_joint
      - sdh_thumb_3_joint