arm:
  kinematics_solver: mdr_lwr_kinematics/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.1
  kinematics_solver_timeout: 0.1
  kinematics_solver_attempts: 1
#head:
#  kinematics_solver: mdr_cob_head_kinematics::head_kinematics_plugin
#  kinematics_solver_search_resolution: 0.1
#  kinematics_solver_timeout: 0.1
#  kinematics_solver_attempts: 1
