arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.1
  kinematics_solver_attempts: 3
head:
  kinematics_solver: mdr_cob_head_kinematics::head_kinematics_plugin
  kinematics_solver_search_resolution: 0.1
  kinematics_solver_timeout: 0.1
  kinematics_solver_attempts: 1